// Accessor + capability gate for the 3D assets generated by
// scripts/generate_3d_assets.py (gaussian splat .sog files for the lightbox
// "View in 3D" mode + depth-map PNGs for the gallery hover parallax).
//
// splatManifest.generated.json maps each served photo's src path to
// { fov, sog, depth, bytes } — see the pipeline script for the schema.
// Photos missing from the manifest simply don't get 3D affordances.

import manifest from './splatManifest.generated.json' with { type: 'json' };

const safeDecode = (s) => {
    try {
        return decodeURIComponent(s);
    } catch {
        return s;
    }
};

// Manifest keys are raw paths; srcs from images.js are URI-encoded
// (same decode fallback as PhotoImage's manifest lookup).
export const splatFor = (src) =>
    (src && (manifest[src] || manifest[safeDecode(src)])) || null;

// 3D effects are desktop-only: they need a hovering fine pointer, and we
// honor reduced-motion. Evaluated lazily so prerender (no window) is safe.
export const supports3D = () =>
    typeof window !== 'undefined' &&
    window.matchMedia('(hover: hover) and (pointer: fine)').matches &&
    !window.matchMedia('(prefers-reduced-motion: reduce)').matches;

export const formatMB = (bytes) => `${(bytes / 1e6).toFixed(1)} MB`;
